sudo: required
dist: xenial

script:
  - bash -xve ./test/travis_ros_install.bash
  - source /opt/ros/indigo/setup.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash

